apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-logstash
spec:
  replicas: 2
  selector:
    matchLabels:
      task: collect-user
      k8s-app: logstash
  template:
    metadata:
      labels:
        task: collect-user
        k8s-app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash-oss:7.10.2
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /usr/share/logstash/config
          name: config-volume
        - mountPath: /usr/share/logstash/pipeline
          name: logstash-pipeline-volume
      volumes:
      - name: config-volume
        configMap:
          name: logstash-configmap
          items:
          - key: logstash.yml
            path: logstash.yml
      - name: logstash-pipeline-volume
        configMap:
          name: logstash-configmap
          items:
          - key: user-logstash.conf
            path: logstash.conf
